FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye

COPY ./.devcontainer/files/.bash_profile /root/.bash_profile
RUN pip3 install --user pdm
# RUN apt update && apt install -y openjdk-11-jdk
